<?php

// @codingStandardsIgnoreFile

?>
<?php
    /** @var \Ripen\Prophet21\Block\Order\BackOrder $block */
    $_orders = $block->getOrders();
?>

<?php if ($_orders && count($_orders)): ?>
    <div class="orders-history__wrapper">
<?php endif; ?>

<?php echo $block->getChildHtml('info');?>
<?php if ($_orders && count($_orders)): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                <?php /* @noEscape */ echo $block->getChildHtml('extra.column.header');?>
                <th scope="col" class="col po-number"><?php /* @escapeNotVerified */ echo __('PO Number') ?></th>
                <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Ship To') ?></th>
                <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra): ?>
                        <?php $extra->setOrder($_order); ?>
                        <?php /* @noEscape */ echo $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('PO Number')) ?>" class="col po-number"><?php echo $block->getOrderPoNumber($_order); ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action view">
                            <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have no open backorders.'); ?></span></div>
<?php endif ?>

<?php if ($_orders && count($_orders)): ?>
    </div>
<?php endif; ?>
