<?php

// @codingStandardsIgnoreFile

?>
<?php
    /** @var \Ripen\Prophet21\Block\Order\History $block */
    $_orders = $block->getOrderHistory();
?>

<form action="" class="order-filters">
    <div class="filters">
        <div class="field form-inline">
            <label>Item Name/SKU: </label>
            <div class="control">
                <input type="text" class="input-text" id="order_filter_keyword" name="keyword" value="<?php echo $block->getRequestParam('keyword');?>" />
            </div>
        </div>

        <div class="field form-inline">
            <label>Quantity Ordered: </label>
            <div class="control">
                <input type="number" class="input-text" id="order_filter_qty" name="qty" value="<?php echo $block->getRequestParam('qty');?>" />
            </div>
        </div>

        <div class="field form-inline">
            <label>From: </label>
            <div class="control">
                <input type="text" class="input-text order-filter-date" id="order_filter_from_date" autocomplete="off" name="from_date" value="<?php echo $block->getRequestParam('from_date');?>" />
                <span class="field-icon fa fa-calendar" aria-hidden="true"></span>
            </div>
        </div>

        <div class="field form-inline">
            <label>To: </label>
            <div class="control">
                <input type="text" class="input-text order-filter-date" id="order_filter_to_date" autocomplete="off" name="to_date" value="<?php echo $block->getRequestParam('to_date');?>" />
                <span class="field-icon fa fa-calendar" aria-hidden="true"></span>
            </div>
        </div>

        <div class="actions-toolbar">
            <div class="secondary">
                <button class="action" type="submit">
                    <span>Apply Filters</span>
                </button>
            </div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'mage/translate',
            'mage/calendar'
        ], function ($, $t) {
            $('.order-filter-date').calendar({
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                currentText: $t('Go Today'),
                closeText: $t('Close'),
                showWeek: true
            });
        })
    </script>

<?php if ($_orders && count($_orders)): ?>
    <div class="orders-history__wrapper">
<?php endif; ?>

<?php echo $block->getChildHtml('info');?>
<?php if ($_orders && count($_orders)): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                <?php /* @noEscape */ echo $block->getChildHtml('extra.column.header');?>
                <th scope="col" class="col po-number"><?php /* @escapeNotVerified */ echo __('PO Number') ?></th>
                <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Ship To') ?></th>
                <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra): ?>
                        <?php $extra->setOrder($_order); ?>
                        <?php /* @noEscape */ echo $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('PO Number')) ?>" class="col po-number"><?php echo $_order->getPoNumber(); ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action view">
                            <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                        </a>
                        <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('No orders found.'); ?></span></div>
<?php endif ?>

<?php if ($_orders && count($_orders)): ?>
    </div>
<?php endif; ?>

</form>
